### ISSUE TITLE
ERROR in ViewportModule is not an NgModule

### ISSUE THREAD

**Issue by iliagerman** [alisahinozcelik/angular2-viewport#7]
Hi,
I receive the following error: ERROR in ViewportModule is not an NgModule.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle myappv2@0.0.0~prebuild: myappv2@0.0.0
6 silly lifecycle myappv2@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle myappv2@0.0.0~build: myappv2@0.0.0
8 verbose lifecycle myappv2@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle myappv2@0.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/iliagerman/Documents/MyApp/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle myappv2@0.0.0~build: CWD: /Users/iliagerman/Documents/MyApp
11 silly lifecycle myappv2@0.0.0~build: Args: [ '-c', 'ng build' ]
12 silly lifecycle myappv2@0.0.0~build: Returned: code: 1  signal: null
13 info lifecycle myappv2@0.0.0~build: Failed to exec build script
14 verbose stack Error: myappv2@0.0.0 build: `ng build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid myappv2@0.0.0
16 verbose cwd /Users/iliagerman/Documents/MyApp
17 error Darwin 16.7.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error myappv2@0.0.0 build: `ng build`
22 error Exit status 1
23 error Failed at the myappv2@0.0.0 build script 'ng build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the myappv2 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ng build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs myappv2
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls myappv2
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by sannankhalid** [comment]
I am also getting this error while starting server, once error populated then i change(add new line) in file and the error vanished but its getting error upon server start.

**Comment by numerized** [comment]
Yes I have the error : Error: Unexpected value 'ViewportModule

**Comment by numerized** [comment]
Any news regarding AOT compilation?
:))

**Comment by hamzawii** [comment]
Same Pb :( , is there any solution to fixe this ?
